// ══════════════════════════════════════════════════════════════
// Test Cases Routes — Serve test suite catalog to the frontend
// ══════════════════════════════════════════════════════════════

import { Router } from "express";

const router = Router();

const testSuites: Record<string, string[]> = {
    'MAINTENANCE': [
        'tc_bi_restore_configuration', 'tc_bi_stop_transactions', 'tc_bi_clear_cache',
        'tc_bi_clear_local_auth_list', 'tc_bi_restore_availability', 'tc_bi_reset_hard',
    ],
    'Authorization': ['TC_023_4_CS', 'TC_023_5_CS', 'TC_024_CS', 'TC_061_1_CS', 'TC_061_2_CS'],
    'DataTransfer': ['TC_062_CS'],
    'FirmwareManagement': ['TC_044_1_CS', 'TC_044_2_CS', 'TC_044_3_CS', 'TC_045_1_CS', 'TC_045_2_CS'],
    'LocalAuthList': ['TC_008_1_CS', 'TC_008_2_CS', 'TC_042_1_CS', 'TC_042_2_CS', 'TC_043_1_CS', 'TC_043_2_CS', 'TC_043_3_CS', 'TC_043_CS'],
    'MeterValues': ['TC_070_CS', 'TC_071_CS'],
    'Provisioning': ['TC_001_CS', 'TC_002_CS', 'TC_013_CS', 'TC_014_CS', 'TC_015_CS', 'TC_016_CS', 'TC_019_CS', 'TC_021_CS', 'TC_032_1_CS', 'TC_032_2_CS', 'TC_034_CS', 'TC_040_1_CS', 'TC_040_2_CS', 'TC_041_CS'],
    'RemoteControl': ['TC_010_CS', 'TC_011_1_CS', 'TC_011_2_CS', 'TC_012_CS', 'TC_017_1_CS', 'TC_017_2_CS', 'TC_018_1_CS', 'TC_018_2_CS', 'TC_026_CS', 'TC_027_CS', 'TC_028_CS', 'TC_030_CS', 'TC_031_CS'],
    'RemoteTrigger': ['TC_054_CS', 'TC_055_CS'],
    'Reservation': ['TC_046_1_CS', 'TC_046_2_CS', 'TC_047_CS', 'TC_048_1_CS', 'TC_048_2_CS', 'TC_048_3_CS', 'TC_048_4_CS', 'TC_049_CS', 'TC_050_1_CS', 'TC_050_2_CS', 'TC_050_3_CS', 'TC_050_4_CS', 'TC_051_CS', 'TC_052_CS', 'TC_053_1_CS', 'TC_053_2_CS'],
    'Security': ['TC_073_CS', 'TC_074_CS', 'TC_075_1_CS', 'TC_075_2_CS', 'TC_076_CS', 'TC_077_CS', 'TC_078_CS', 'TC_079_CS', 'TC_080_CS', 'TC_081_CS', 'TC_083_CS', 'TC_084_CS', 'TC_085_CS', 'TC_086_CS', 'TC_087_CS'],
    'SmartCharging': ['TC_056_CS', 'TC_057_CS', 'TC_058_1_CS', 'TC_058_2_CS', 'TC_059_CS', 'TC_060_CS', 'TC_066_CS', 'TC_067_CS', 'TC_072_CS', 'TC_082_CS'],
    'Transactions': ['TC_003_CS', 'TC_004_1_CS', 'TC_004_2_CS', 'TC_005_1_CS', 'TC_005_2_CS', 'TC_005_3_CS', 'TC_007_1_CS', 'TC_007_2_CS', 'TC_036_CS', 'TC_037_1_CS', 'TC_037_2_CS', 'TC_037_3_CS', 'TC_038_CS', 'TC_039_CS', 'TC_068_CS', 'TC_069_CS'],
};

const testDescriptions: Record<string, string> = {
    'TC_001_CS': 'Boot notification — accepted',
    'TC_002_CS': 'Boot notification — pending',
    'TC_003_CS': 'Start transaction — valid',
    'TC_004_1_CS': 'Stop transaction — by identifier',
    'TC_004_2_CS': 'Stop transaction — by evse',
    'TC_005_1_CS': 'Transaction event — started',
    'TC_005_2_CS': 'Transaction event — updated',
    'TC_005_3_CS': 'Transaction event — ended',
    'TC_007_1_CS': 'Meter values — during idle',
    'TC_007_2_CS': 'Meter values — during transaction',
    'TC_008_1_CS': 'Authorize — valid idToken',
    'TC_008_2_CS': 'Authorize — invalid idToken',
    'TC_010_CS': 'Remote start — accepted',
    'TC_011_1_CS': 'Remote stop — accepted',
    'TC_011_2_CS': 'Remote stop — unknown transaction',
    'TC_012_CS': 'Unlock connector',
    'TC_013_CS': 'Reset — immediate',
    'TC_014_CS': 'Reset — on idle',
    'TC_015_CS': 'Status notification — operational',
    'TC_016_CS': 'Status notification — faulted',
    'TC_017_1_CS': 'Trigger message — requested',
    'TC_017_2_CS': 'Trigger message — not supported',
    'TC_018_1_CS': 'Trigger message — heartbeat',
    'TC_018_2_CS': 'Trigger message — meter values',
    'TC_019_CS': 'Heartbeat — basic',
    'TC_021_CS': 'Get base report — full inventory',
    'TC_023_4_CS': 'Authorize — list version 0',
    'TC_023_5_CS': 'Authorize — list version 1',
    'TC_024_CS': 'Send local list — full update',
    'TC_026_CS': 'Clear cache — accepted',
    'TC_027_CS': 'Data transfer — CSMS to CS',
    'TC_028_CS': 'Data transfer — CS to CSMS',
    'TC_030_CS': 'Get configuration — key values',
    'TC_031_CS': 'Get variables — single',
    'TC_032_1_CS': 'Set variables — single',
    'TC_032_2_CS': 'Set variables — multiple',
    'TC_034_CS': 'Change availability — operative',
    'TC_036_CS': 'Cost updated — notification',
    'TC_037_1_CS': 'Customer information — basic',
    'TC_037_2_CS': 'Customer information — with report',
    'TC_037_3_CS': 'Customer information — privacy',
    'TC_038_CS': 'Get monitoring report — full',
    'TC_039_CS': 'Notify event — single',
    'TC_040_1_CS': 'Clear hero — single',
    'TC_040_2_CS': 'Clear hero — multiple',
    'TC_041_CS': 'Get installed certificate IDs',
    'TC_042_1_CS': 'Install certificate — V2G',
    'TC_042_2_CS': 'Install certificate — CSMS',
    'TC_043_1_CS': 'Get local list version',
    'TC_043_2_CS': 'Get local list — version 0',
    'TC_043_3_CS': 'Get local list — version 1',
    'TC_043_CS': 'Get local list version — default',
    'TC_044_1_CS': 'Update firmware — accepted',
    'TC_044_2_CS': 'Update firmware — rejected',
    'TC_044_3_CS': 'Update firmware — status',
    'TC_045_1_CS': 'Publish firmware — accepted',
    'TC_045_2_CS': 'Publish firmware — rejected',
    'TC_046_1_CS': 'Reserve now — accepted',
    'TC_046_2_CS': 'Reserve now — expired',
    'TC_047_CS': 'Cancel reservation',
    'TC_048_1_CS': 'Reserve now — connector',
    'TC_048_2_CS': 'Reserve now — evse',
    'TC_048_3_CS': 'Reserve now — overwrite',
    'TC_048_4_CS': 'Reserve now — idempotent',
    'TC_049_CS': 'Reservation status update',
    'TC_050_1_CS': 'Request start — accepted',
    'TC_050_2_CS': 'Request start — rejected',
    'TC_050_3_CS': 'Request stop — accepted',
    'TC_050_4_CS': 'Request stop — rejected',
    'TC_051_CS': 'Reserve now — concurrent',
    'TC_052_CS': 'Cancel reservation — unknown',
    'TC_053_1_CS': 'Reserve now — group id',
    'TC_053_2_CS': 'Cancel reservation — group id',
    'TC_054_CS': 'Trigger message — evse deployed',
    'TC_055_CS': 'Trigger message — connector deployed',
    'TC_056_CS': 'Set charging profile — accepted',
    'TC_057_CS': 'Get composite schedule',
    'TC_058_1_CS': 'Charging profile — power constraint',
    'TC_058_2_CS': 'Charging profile — energy constraint',
    'TC_059_CS': 'Clear charging profile',
    'TC_060_CS': 'Get charging profiles',
    'TC_061_1_CS': 'Notify authorization — accepted',
    'TC_061_2_CS': 'Notify authorization — rejected',
    'TC_062_CS': 'Data transfer — CSMS initiated',
    'TC_066_CS': 'Report charging profiles — accepted',
    'TC_067_CS': 'Report charging profiles — rejected',
    'TC_068_CS': 'Transaction event — energy values',
    'TC_069_CS': 'Transaction event — power values',
    'TC_070_CS': 'Meter values — voltage',
    'TC_071_CS': 'Meter values — current',
    'TC_072_CS': 'Set variable monitoring — accepted',
    'TC_073_CS': 'Certificate signed — V2G',
    'TC_074_CS': 'Certificate signed — CSMS',
    'TC_075_1_CS': 'Sign certificate — V2G',
    'TC_075_2_CS': 'Sign certificate — CSMS',
    'TC_076_CS': 'Security event notification',
    'TC_077_CS': 'Get installed certificate IDs — V2G',
    'TC_078_CS': 'Get installed certificate IDs — CSMS',
    'TC_079_CS': 'Get installed certificate IDs — combined',
    'TC_080_CS': 'Install certificate — combined',
    'TC_081_CS': 'Delete certificate — accepted',
    'TC_082_CS': 'Clear variable monitoring',
    'TC_083_CS': 'Delete certificate — V2G',
    'TC_084_CS': 'Delete certificate — CSMS',
    'TC_085_CS': 'Get report — component variables',
    'TC_086_CS': 'Notify report — component variables',
    'TC_087_CS': 'Set monitoring base — all',
    'tc_bi_restore_configuration': 'Maintenance — restore configuration',
    'tc_bi_stop_transactions': 'Maintenance — stop all transactions',
    'tc_bi_clear_cache': 'Maintenance — clear cache',
    'tc_bi_clear_local_auth_list': 'Maintenance — clear local auth list',
    'tc_bi_restore_availability': 'Maintenance — restore availability',
    'tc_bi_reset_hard': 'Maintenance — hard reset',
};

router.get("/", (_req, res) => {
    res.json(testSuites);
});

router.get("/details", (_req, res) => {
    res.json(testDescriptions);
});

export default router;
